### ISSUE TITLE
Make template inclusion conditional

### ISSUE THREAD

**Issue by kupuguy** [Lacrymology/django-google-tag-manager#2]
This is a feature request. Add a test to the htm.html template to only include the Google Tag Manager code when google_tag_id is set.

This allows the analytics code to be excluded entirely when running test instances simply by insuring that in those configurations settings.GOOGLE_TAG_ID is an empty string.

**Comment by Lacrymology** [comment]
This was fixed in https://github.com/Lacrymology/django-google-tag-manager/commit/ed5b42495e341dedb0d9da06757b099bb7f261f2
