### ISSUE TITLE
Should the Tag Manager code be in two templatetags?

### ISSUE THREAD

**Issue by maxpeterson** [Lacrymology/django-google-tag-manager#3]
It looks like Google no recomend the Tag Manager code is split with one part in the head and one in the body https://developers.google.com/tag-manager/quickstart there is a write up of the changes here http://dmitriilin.com/where-to-place-google-tag-manager-code-v-2/

Do you have any intention or interest in including two templatetags, one for the body and one for the head? This could be a backwardly compatible change by creating two new templatetags, leaving the old one two output both tags.

**Comment by Lacrymology** [comment]
Sure, I'm not currently using this code, but I'll update that. Or do you have any proposed code for this?

**Comment by Lacrymology** [comment]
Someone already did this: I opened a PR for myself to see if there's anything else that needs to be done:

https://github.com/Lacrymology/django-google-tag-manager/pull/4

**Comment by maxpeterson** [comment]
Wow - I was going to offer to do this. I will take a look at the PR

**Comment by Lacrymology** [comment]
Fixed with #5 and pushed `v0.0.3` to PyPi

**Comment by maxpeterson** [comment]
Thanks @Lacrymology and @olegserov
